# Generated by Django 4.2.7 on 2023-11-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('proyecto', models.CharField(choices=[('todos', 'Todos'), ('particular', 'Particular')], max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_activo', models.CharField(choices=[('general', 'General'), ('vigente', 'Vigente'), ('baja', 'Dado de baja')], max_length=50)),
                ('ordenar_por', models.CharField(choices=[('fecha', 'Fecha'), ('activo', 'Activo')], max_length=50)),
            ],
        ),
    ]
