# Generated by Django 4.2.7 on 2023-11-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado_activo',
            field=models.CharField(choices=[('general', 'General'), ('vigente', 'Vigente'), ('dado_de_baja', 'Dado de baja')], max_length=50),
        ),
    ]
