# Generated by Django 4.2.7 on 2023-11-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0006_customuser_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='default_value', max_length=128),
            preserve_default=False,
        ),
    ]
