# Generated by Django 4.2.7 on 2023-11-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0007_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('estado_activo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo_titulo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activo',
            name='estado_activo',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='ordenar_por',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='proyecto',
        ),
    ]
